---
# Retrieve the current hostname, because {{ ansible_hostname }} still contains the old name
- shell: hostname
  register: current_hostname

- name: Install Mysql package
  yum: name={{ item }} state=installed
  sudo: yes
  with_items:
   - mysql-server
   - MySQL-python
   - libselinux-python
   - libsemanage-python

- name: Update Configuration
  sudo: yes
  template:
    src: my.cnf.j2
    dest: /etc/my.cnf
    owner: root
    group: root
    mode: 0644

- name: mysqld start
  sudo: yes
  service:
    name=mysqld
    state=started
    enabled=yes

- name: Create databases
  sudo: yes
  mysql_db: name={{ dbname }} state=present login_user={{ dbuser }} login_password={{ upassword }}

- name: Ensure anonymous users are not in the database
  mysql_user: name='' host={{ item }} state=absent login_user={{ dbuser }} login_password={{ upassword }}
  with_items:
    - localhost
    - "{{ current_hostname.stdout | lower }}"

- name: Create users
  mysql_user: name={{ dbuser }} password={{ upassword }} priv={{ dbname }}.*:ALL state=present login_user={{ dbuser }} login_password={{ upassword }}
