---
- name: Install apps
  yum: name={{ item }} state=present
  sudo: yes
  with_items:
    - git
    - vim
    - wget
    - tree
    - policycoreutils-python
    - libsemanage-python
    - libselinux-python
