---
- name: apply common configuration to all nodes
  hosts: dbservers
  remote_user: root

#  roles:
#    - common

- name: deploy MySQL and configure the databases
  hosts: dbservers
  remote_user: root

  roles:
    - db
