---
- name: apply common configuration to all nodes
  hosts: webservers
  remote_user: root

  roles:
    - common

- name: configure and deploy the webservers and application code
  hosts: webservers
  remote_user: root

  roles:
    - web
