---
# Handler for the webtier: handlers are called by other plays.
# See http://docs.ansible.com/playbooks_intro.html for more information about handlers.

- name: restart iptables
  sudo: yes
  service: name=iptables state=restarted

- name: restart httpd
  sudo: yes
  service: name=httpd state=restarted